// Controls the type of `import("cloudflare:test").env` in tests.
// `Env` is generated by `wrangler types src/worker-configuration.d.ts`.
// ProvidedEnv extends it so tests get fully-typed bindings:
//   env.SESSIONS_DB  → D1Database
//   env.CONFIG       → KVNamespace
//   env.ASSETS       → R2Bucket
//   etc.
//
// Run `pnpm --filter @piccolo/core types` to regenerate after changing wrangler.template.jsonc.
declare module "cloudflare:test" {
  interface ProvidedEnv extends Env {}
}

// Augment Vitest's ProvidedContext so that inject("migrations") is typed.
// The `migrations` value is populated by `test.provide` in vitest.config.ts
// using `readD1Migrations` from `@cloudflare/vitest-pool-workers/config`.
// D1Migration is exported from the main package entry in @cloudflare/vitest-pool-workers 0.13+
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare module "vitest" {
  interface ProvidedContext {
    migrations: D1Migration[];
  }
}
