// Controls the type of `import("cloudflare:workers").env` in tests.
// ProvidedEnv is extended from Env which is generated by `wrangler types`.
// Run `pnpm --filter @piccolo/core types` to regenerate worker-configuration.d.ts.
declare module "cloudflare:workers" {
  // biome-ignore lint/suspicious/noExplicitAny: Env is generated by wrangler types; not yet available at scaffold time
  interface ProvidedEnv extends Record<string, any> {}
}
