// Controls the type of `import("cloudflare:test").env` in tests.
// `Env` is generated by `wrangler types src/worker-configuration.d.ts`.
// For ext-fetch-tool, Env is empty (no bindings required).
declare module "cloudflare:test" {
  interface ProvidedEnv extends Env {}
}
