// Controls the type of `import("cloudflare:test").env` in tests.
// `Env` is generated by `wrangler types src/worker-configuration.d.ts`.
// ProvidedEnv extends it so tests get fully-typed bindings:
//   env.INSTRUCTIONS_DB → D1Database
//
// Run `pnpm --filter @piccolo/ext-instructions types` to regenerate after changing wrangler.template.jsonc.
declare module "cloudflare:test" {
  interface ProvidedEnv extends Env {}
}

// Augment Vitest's ProvidedContext so that inject("migrations") is typed.
// The `migrations` value is populated by `test.provide` in vitest.config.ts
// using `readD1Migrations` from `@cloudflare/vitest-pool-workers`.
import type { D1Migration } from "@cloudflare/vitest-pool-workers";

declare module "vitest" {
  interface ProvidedContext {
    migrations: D1Migration[];
  }
}
